server:            
  ros__parameters:
    autostart: true
    livox_cfg_path: "/home/alessio/Desktop/dafn25_mid360_driver/install/livox_mid360_driver/share/livox_mid360_driver/config/mid360_config.json"
